### ISSUE TITLE
Make baladmin command send a message to the target player when executed

### ISSUE THREAD

**Issue by Soof4** [Soof4/ComfyEconomy#11]

**Comment by Hex4gonForc3** [comment]
Bro why this error
![Uploading Screenshot_2024-03-15-12-19-43-27.jpg…]()

**Comment by Hex4gonForc3** [comment]
![Screenshot_2024-03-15-12-19-43-27](https://github.com/Soof4/ComfyEconomy/assets/153827257/ce985d1d-b2b0-480a-83ff-902179d4a149)
Bro why this error

**Comment by Hex4gonForc3** [comment]
![Screenshot_2024-03-15-05-20-05-20](https://github.com/Soof4/ComfyEconomy/assets/153827257/8ca33d46-7478-4014-8607-f7ac54d82733)
Bro why this error

**Comment by Soof4** [comment]
> ![Screenshot_2024-03-15-05-20-05-20](https://private-user-images.githubusercontent.com/153827257/313111134-8ca33d46-7478-4014-8607-f7ac54d82733.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDExNjYsIm5iZiI6MTcxMDUwMDg2NiwicGF0aCI6Ii8xNTM4MjcyNTcvMzEzMTExMTM0LThjYTMzZDQ2LTc0NzgtNDAxNC04NjA3LWY3YWM1NGQ4MjczMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxMTA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODdmNDIyYWU5MmRmZjE1MDA0ZmVjMzQ4MTk4MTVhYzkzYWNmOGI3OTRjYWQ3ZDc0ZmY5NmVjMGQ3M2E0NzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YSPfijcnX8-eNDa7VcZXoV2HFFE3ohFflFqj8SHriRc) Bro why this error

it looks like your shop sign is messed up, can you send a picture of the text on the sign?

**Comment by Soof4** [comment]
Implemented with 2eef7426ea8807af088af4118e8deccbb220bbc8.
